# -*- coding: utf-8 -*-
"""FraudShield_Banking_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwlvRsh39EYEB6r_SMIl1kS6KnV_31P8
"""

import os
import kagglehub
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("algozee/financial-transaction-fraud-dataset")

print("Path to dataset files:", path)

df = pd.read_csv(os.path.join(path, "FraudShield_Banking_Data.csv"))
print(f'Number of rows: {df.shape[0]} | Number of columns:{df.shape[1]}')
print(f'Fraud Label : {df['Fraud_Label'].value_counts(normalize=True)}')
print(df)

"""Convert Yes/No -> 1/0"""

binary_cols = [
    'Is_International_Transaction',
    'Is_New_Merchant',
    'Unusual_Time_Transaction'
]

for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

"""Gestion de l'heure et de la date

"""

from copy import error
df['Transaction_Time'] = pd.to_datetime(df['Transaction_Time'], format = '%H:%M', errors = 'coerce')
df['Hour'] = df['Transaction_Time'].dt.hour
df['Minute'] = df['Transaction_Time'].dt.minute

df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], format = '%Y-%m-%d', errors = 'coerce')
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

"""Inspection des valeurs nulles dans les variables numerics"""

df.isnull().sum().sort_values(ascending=False)

"""Imputation des variables maquantes numeric par la moyenne et les variables categorielles par le mode"""

# Récupérer les noms des colonnes numériques (int64 et float64)
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
# Imputer les valeurs manquantes des colonnes numériques par la moyenne
if not numeric_cols.empty:
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Récupérer les noms des colonnes catégorielles (object)
object_cols = df.select_dtypes(include=['object']).columns
# Imputer les valeurs manquantes des colonnes catégorielles par le mode
if not object_cols.empty:
    for col in object_cols:
        if df[col].isnull().any(): # Vérifier s'il y a des NaN à traiter
            if not df[col].mode().empty: # S'assurer qu'il y a un mode à utiliser
                df[col] = df[col].fillna(df[col].mode()[0])

"""Veification des veleurs nulles"""

df.isnull().sum().sort_values(ascending=False)

"""Véfication des valeurs doubles"""

number_duplicate = df.duplicated().sum()
print(f'Number of duplicate rows: {number_duplicate}')

"""Recuperer une copie de la base de données"""

clean_df = df.copy()

"""Suppression des colonnes"""

clean_df = df.drop(['Transaction_ID', 'Customer_ID', 'Merchant_ID', 'Device_ID', 'Transaction_Time', 'Transaction_Date', 'IP_Address'], axis=1)

"""Extraction des données numériques et catégorielles et cible"""

numeric_df = clean_df.select_dtypes(include=['int64', 'float64'])
categorical_df = clean_df.select_dtypes(include=['object'])
categorical_df.head(5)

"""Extraction de la variable cible et conversion des valeurs en numeriques : Normal/Fraud -> 1/0"""

target_df = df['Fraud_Label']
# Handle NaN values before converting to integer by filling with the mode
target_df = target_df.fillna(target_df.mode()[0])
print('conversion des valeurs en numeriques Normal/Fraud -> 1/0')
target_df = target_df.map({'Normal': 1, 'Fraud': 0})
print('convert target_df en integer')
target_df = target_df.astype(int)
target_df.head(5)

"""EDA"""

print(df['Fraud_Label'].value_counts())
print(df['Fraud_Label'].value_counts(normalize=True) * 100)

print('Information sur la taille du dataset')
print(f'Number of rows: {df.shape[0]} | Number of columns:{df.shape[1]}')
print('Information sur le dataset')
df.info()
print('Description du dataset')
df.describe()
print('Analyse des valeurs manquantes')
print(df.isnull().sum().sort_values(ascending=False))
print('Analyse des valeurs dupliquées')
print(df.duplicated().sum())
print('distibution de Fraud_Label')
df['Fraud_Label'].value_counts().plot(kind='bar')

"""Quelques analyses de corrélation entre les variables"""

print('Analyse de corrélation entre les variables et la variable cible')
print(numeric_df.corrwith(target_df))

"""### Interprétation de la  Matrice de Corrélation

#### Corrélation entre les Variables Numériques et la Variable Cible (`numeric_df.corrwith(target_df)`)

Cette analyse est cruciale car elle révèle quelles variables numériques ont la plus forte relation linéaire avec la variable `Fraud_Label` (où `Normal` est 1 et `Fraud` est 0). Une corrélation positive signifie qu'une augmentation de la variable numérique est associée à une plus grande probabilité d'être `Normal` (moins de fraude), tandis qu'une corrélation négative signifie une association avec `Fraud`.

*   **`Is_International_Transaction`**: Montre une corrélation négative relativement notable (environ -0.06). Cela suggère que les transactions internationales sont légèrement plus susceptibles d'être frauduleuses.
*   **`Unusual_Time_Transaction`**: Présente également une corrélation négative (environ -0.059), indiquant que les transactions effectuées à des heures inhabituelles sont légèrement plus associées à la fraude.
*   **`Distance_From_Home`**: A une faible corrélation positive (environ 0.01), ce qui pourrait indiquer qu'une plus grande distance par rapport au domicile est très légèrement associée à des transactions normales. Cependant, la valeur est très faible.

Les autres variables numériques montrent des corrélations très faibles (proches de zéro) avec `Fraud_Label`, ce qui signifie qu'elles ont une faible relation linéaire directe avec la détection de la fraude. Cela ne signifie pas qu'elles sont inutiles, mais que leur influence pourrait être non linéaire ou liée à d'autres variables.

Visualisations graphiques
"""

