# -*- coding: utf-8 -*-
"""01_Data_Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7LmeoTkHkhOpzCxWz5RDF0pNPCC8uNU
"""

import os
import kagglehub
import pandas as pd

"""Chargement du dataset"""

# Download latest version
path = kagglehub.dataset_download("algozee/financial-transaction-fraud-dataset")

print("Path to dataset files:", path)

df = pd.read_csv(os.path.join(path, "FraudShield_Banking_Data.csv"))
print(f'Number of rows: {df.shape[0]} | Number of columns:{df.shape[1]}')
print(f'Fraud Label : {df['Fraud_Label'].value_counts(normalize=True)}')

"""EDA"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Rapport EDA")
profile.to_notebook_iframe()

!git clone https://github.com/taponjou/Fraud-Detection-Project.git