# -*- coding: utf-8 -*-
"""02_Data_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGxD24iezbCMQYNJKwPcRcdERPDW8fIm
"""

import os
import kagglehub
import pandas as pd

# Code for local download as requested by the user
from google.colab import files
from sklearn.model_selection import train_test_split

"""Chargement du dataset"""

# Download latest version
path = kagglehub.dataset_download("algozee/financial-transaction-fraud-dataset")

print("Path to dataset files:", path)

df = pd.read_csv(os.path.join(path, "FraudShield_Banking_Data.csv"))
print(f'Number of rows: {df.shape[0]} | Number of columns:{df.shape[1]}')
print(f'Fraud Label : {df['Fraud_Label'].value_counts(normalize=True)}')

"""Convertion Yes/No -> 1/0"""

binary_cols = [
    'Is_International_Transaction',
    'Is_New_Merchant',
    'Unusual_Time_Transaction'
]

for col in binary_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .map({'yes': 1, 'no': 0})
    )
for col in binary_cols:
    df[col] = df[col].astype("Int64")
print(df[['Is_International_Transaction', 'Is_New_Merchant', 'Unusual_Time_Transaction']])

"""Gestion de l'heure"""

from copy import error
df['Transaction_Time'] = pd.to_datetime(df['Transaction_Time'], format = '%H:%M', errors = 'coerce')
df['Hour'] = df['Transaction_Time'].dt.hour
df['Minute'] = df['Transaction_Time'].dt.minute

df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], format = '%Y-%m-%d', errors = 'coerce')
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

"""Imputation des variables maquantes numeric par la moyenne et les variables categorielles par le mode"""

# Récupérer les noms des colonnes numériques standard (float64, numpy int64)
# Ces colonnes peuvent être imputées par la moyenne.
standard_numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Récupérer les noms des colonnes de type 'Int64' (entier nullable de pandas)
# Ces colonnes sont souvent des drapeaux binaires et sont mieux imputées par le mode.
nullable_int_cols = df.select_dtypes(include=['Int64']).columns

# S'assurer qu'aucune colonne Int64 n'est incluse par inadvertance dans standard_numeric_cols
# Cette étape rend l'imputation plus robuste.
standard_numeric_cols = standard_numeric_cols.drop(nullable_int_cols, errors='ignore')

if not standard_numeric_cols.empty:
    df[standard_numeric_cols] = df[standard_numeric_cols].fillna(df[standard_numeric_cols].mean())

# Imputer les valeurs manquantes des colonnes de type 'Int64' par le mode.
if not nullable_int_cols.empty:
    for col in nullable_int_cols:
        if df[col].isnull().any():
            if not df[col].mode().empty:
                df[col] = df[col].fillna(df[col].mode()[0])

# Récupérer les noms des colonnes catégorielles (object)
# Ces colonnes sont imputées par le mode.
object_cols = df.select_dtypes(include=['object']).columns
if not object_cols.empty:
    for col in object_cols:
        if df[col].isnull().any():
            if not df[col].mode().empty:
                df[col] = df[col].fillna(df[col].mode()[0])

"""Vérification des veleurs nulles"""

df.isnull().sum().sort_values(ascending=False)

"""Véfication des valeurs doubles"""

number_duplicate = df.duplicated().sum()
print(f'Number of duplicate rows: {number_duplicate}')

"""Recuperer une copie de la base de données

"""

clean_df = df.copy()

"""Suppression des colonnes"""

clean_df = clean_df.drop(columns=['Transaction_ID', 'Customer_ID', 'Transaction_Time', 'Transaction_Date', 'Merchant_ID', 'Device_ID', 'IP_Address'])

"""Transformation des variables catégorielles en utilisant One-Hot Encodin"""

categorical_cols = [
    'Transaction_Type',
    'Merchant_Category',
    'Transaction_Location',
    'Customer_Home_Location',
    'Card_Type'
]
clean_df = pd.get_dummies(
    clean_df,
    columns=categorical_cols,
    dtype=int
)
print(clean_df)

"""Extraction de la variable cible et conversion des valeurs en numeriques : Normal/Fraud -> 1/0"""

target_df = clean_df['Fraud_Label']
# Handle NaN values before converting to integer by filling with the mode
target_df = target_df.fillna(target_df.mode()[0])
print('conversion des valeurs en numeriques Normal/Fraud -> 1/0')
target_df = target_df.map({'Normal': 0, 'Fraud': 1})
print('convert target_df en integer')
target_df = target_df.astype(int)
target_df.head(5)

"""Séparation des données"""

# X : variables explicatives
# y : variable cible

X = clean_df.drop("Fraud_Label", axis=1)
y = clean_df["Fraud_Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""Sauvegarde des données"""

print("Sauvegarde des données dans un repertoire local")

X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_test.to_csv("y_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)

from google.colab import files

files_to_download = ['X_train.csv', 'X_test.csv', 'y_train.csv', 'y_test.csv']

for f in files_to_download:
    try:
        files.download(f)
    except FileNotFoundError:
        print(f"Erreur: Le fichier '{f}' n'a pas été trouvé dans l'environnement Colab. Assurez-vous qu'il a été sauvegardé.")

!git clone https://github.com/taponjou/Fraud-Detection-Project.git

!pwd

!git status

!git remote -v

!git clone https://github.com/taponjou/Fraud-Detection_Project.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Fraud-Detection-Project

!pwd

!ls -la /content

!git status